"""initial schema

Revision ID: ff11f4f4230d
Revises:
Create Date: 2026-02-09 17:07:45.644840
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ff11f4f4230d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "devices",
        sa.Column("id", sa.UUID(), nullable=False, comment="Unique device identifier (UUID)"),
        sa.Column(
            "device_id",
            sa.String(length=64),
            nullable=False,
            comment="Human-readable device identifier",
        ),
        sa.Column("name", sa.String(length=255), nullable=True, comment="Friendly device name"),
        sa.Column(
            "api_key_hash",
            sa.String(length=128),
            nullable=False,
            comment="Hashed API key for authentication",
        ),
        sa.Column(
            "is_active", sa.Boolean(), nullable=False, comment="Whether device is currently active"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Device registration timestamp (UTC)",
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp of last reading received (UTC)",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_devices_device_id"), "devices", ["device_id"], unique=True)
    op.create_table(
        "readings",
        sa.Column("id", sa.UUID(), nullable=False, comment="Unique reading identifier (UUID)"),
        sa.Column(
            "device_id",
            sa.String(length=64),
            nullable=False,
            comment="Device that produced this reading",
        ),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Server-assigned timestamp (UTC)",
        ),
        sa.Column(
            "temperature", sa.Float(), nullable=True, comment="Temperature in degrees Celsius"
        ),
        sa.Column("humidity", sa.Float(), nullable=True, comment="Relative humidity percentage"),
        sa.Column("voltage", sa.Float(), nullable=True, comment="Power/battery voltage in volts"),
        sa.ForeignKeyConstraint(["device_id"], ["devices.device_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        comment="Immutable sensor readings time-series",
    )
    op.create_index(
        "ix_readings_device_timestamp",
        "readings",
        ["device_id", "timestamp"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        "ix_readings_timestamp", "readings", ["timestamp"], unique=False, postgresql_using="btree"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_readings_timestamp", table_name="readings", postgresql_using="btree")
    op.drop_index("ix_readings_device_timestamp", table_name="readings", postgresql_using="btree")
    op.drop_table("readings")
    op.drop_index(op.f("ix_devices_device_id"), table_name="devices")
    op.drop_table("devices")
    # ### end Alembic commands ###
